name: Update Source
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Generate AltSource
        run: |
          # Используем актуальный и надежный генератор
          npx @altsource/cli@latest generate --config config.json --output apps.json
        continue-on-error: true # Если один из репо в конфиге битый, процесс не прервется

      - name: Commit and Push
        run: |
          git config --global user.name "SourceBot"
          git config --global user.email "bot@example.com"
          git add apps.json
          git commit -m "Update apps.json" || exit 0
          git push
